# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

workspace 'OscletonSDK'

project 'OscletonSample'

target 'OscletonSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OscletonSample

  pod 'OscletonSDK', :path => '../'


#  target 'OscletonSampleTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

#  target 'OscletonSampleUITests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

end
